defmodule JcWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :jc

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_jc_key",
    signing_salt: "EIAs2oBS",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  # dev: tell the browser never to cache static assets, so rebuilt JS/CSS always reaches the page
  # (the browser otherwise serves a stale app.js with `cache-control: public`).
  plug :dev_no_cache_assets

  plug Plug.Static,
    at: "/",
    from: :jc,
    # only serve precompressed .gz in prod; in dev it would serve STALE .gz left by a prior
    # `mix assets.deploy` (Burrito build) instead of the fresh esbuild output (caused a long
    # "my JS change won't take" debug — the browser got the stale gzipped bundle).
    gzip: Mix.env() == :prod,
    only: JcWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  defp dev_no_cache_assets(conn, _opts) do
    Plug.Conn.register_before_send(conn, fn conn ->
      if String.starts_with?(conn.request_path, "/assets/"),
        do: Plug.Conn.put_resp_header(conn, "cache-control", "no-store, must-revalidate"),
        else: conn
    end)
  end

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug JcWeb.Router
end
